name: CI Build
on: [push, workflow_dispatch]

permissions:
  contents: write
  deployments: write

jobs:
  execute:
    name: CI Build
    runs-on: ubuntu-latest
    container:
      image: "continuumio/miniconda3:22.11.1"
    steps:
        uses: actions/checkout@v2
      - name: Install and build
        run: |
          export PATH=/opt/conda/bin:$PATH
          conda env create --name prod_env -f environment_weekly_report.yml --quiet
          conda clean -ay
	  export PYHTONPATH=$HOME/Documents/mu-placebo-api
          export PATH=/opt/conda/envs/prod_env/bin:$PATH
          conda env export --name prod_env
          invoke build
      #     pytest --benchmark-only --benchmark-json benchmark_output.json
      # - name: Store benchmark result
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     tool: 'pytest'
      #     output-file-path: benchmark_output.json
      #     # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     auto-push: true
      #     # Show alert with commit comment on detecting possible performance regression
      #     alert-threshold: '200%'
      #     comment-on-alert: true
      #     fail-on-alert: true
      #     alert-comment-cc-users: '@env-sross,@adrienkergastel,@hafezbazrafshan'
